### ISSUE TITLE
Question: Usage with Electron vs Targeting macOS + windows separately

### ISSUE THREAD

**Issue by christopherhein** [amoghbanta/reactNativeEverywhere#13]
Purely from an educational standpoint what would be the purpose of targeting macOS and Windows as separate components when you could potentially use something like https://github.com/PaulLeCam/react-native-electron to make cross-platform desktop apps that would even include running on linux…

It seems to work with react-native-web obviously like this project it's still very new and probably not 100% ready for primetime but might be something to shortcut the process

**Comment by amoghbanta** [comment]
Hey @christopherhein, the main reason why i preferred keeping some components separate for different platforms was to utilize their native capabilities in the way they demand, which on the other hand increases my control on the application and keeps lower the complexity. It finally boils down to the requirements you have to cater in your project. In my personal opinion and experience, it is always better to separate out the different concerns and handle them differently the way they require or it'll increase the complexity and hinder in the growth of the project. React-native-electron looks promising to me and would save a lot of time and energy if it's offering is matching your requirements. ReactNativeEverywhere tries to give a generic way to cater requirements from prototyping to demanding and complex production apps, which required targeting different platforms as separate components. Hope this answers your question.

**Comment by christopherhein** [comment]
Yeah, that makes a lot of sense - appreciate the response and amazing work so far on the proj!
